[workspace]
members = ["nanomp3-core", "nanomp3", "parity"]
exclude = ["fuzz"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
# 1.80 without the `wide` feature.
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/robbie01/nanomp3"
authors = ["Robert B. Langer <robbie@sohio.net>"]
